# Generated by Django 4.0.3 on 2022-03-06 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
